#!/usr/bin/env python3
"""Check OG-III paper-to-Coq finite witness coverage."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TEX_PATH = ROOT / "observer_geometry_3.tex"
COQ_PATH = ROOT / "formal" / "coq" / "OG3.v"
MANIFEST_PATH = ROOT / "formal" / "coverage.json"
TABLE_PATH = ROOT / "formal" / "generated" / "coverage_table.tex"

THEOREM_ENVS = {"theorem", "proposition", "lemma"}


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def tex_labels(tex: str) -> set[str]:
    return set(re.findall(r"\\label\{([^}]+)\}", tex))


def theorem_like_labels(tex: str) -> set[str]:
    labels: set[str] = set()
    current_env: str | None = None
    for line in tex.splitlines():
        begin = re.search(r"\\begin\{(theorem|proposition|lemma)\}", line)
        if begin:
            current_env = begin.group(1)
        if current_env in THEOREM_ENVS:
            label = re.search(r"\\label\{([^}]+)\}", line)
            if label:
                labels.add(label.group(1))
                current_env = None
        if current_env and re.search(r"\\end\{" + re.escape(current_env) + r"\}", line):
            current_env = None
    return labels


def coq_objects(coq: str) -> set[str]:
    pattern = r"^\s*(?:Example|Theorem|Lemma|Proposition)\s+([A-Za-z0-9_']+)\s*:"
    return set(re.findall(pattern, coq, flags=re.MULTILINE))


def load_manifest() -> list[dict[str, str]]:
    data = json.loads(read(MANIFEST_PATH))
    if not isinstance(data, list):
        raise ValueError("coverage manifest must be a list")
    for index, entry in enumerate(data):
        if not isinstance(entry, dict):
            raise ValueError(f"coverage entry {index} must be an object")
        for key in (
            "id",
            "paper_label",
            "paper_ref",
            "coq_object",
            "kind",
            "status",
            "scope",
        ):
            if key not in entry or not isinstance(entry[key], str) or not entry[key]:
                raise ValueError(f"coverage entry {index} is missing string field {key!r}")
    return data


def tex_escape(value: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "_": r"\_",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(ch, ch) for ch in value)


def tt(value: str) -> str:
    escaped = tex_escape(value)
    escaped = escaped.replace(r"\_", r"\_\allowbreak{}")
    escaped = escaped.replace("-", r"-\allowbreak{}")
    escaped = escaped.replace(":", r":\allowbreak{}")
    escaped = escaped.replace(".", r".\allowbreak{}")
    return r"\texttt{" + escaped + "}"


def generate_table(entries: list[dict[str, str]]) -> str:
    lines = [
        r"% Generated by formal/check_coverage.py; do not edit by hand.",
        r"\begingroup",
        r"\footnotesize",
        r"\begin{xltabular}{\textwidth}{>{\raggedright\arraybackslash}p{0.20\textwidth}>{\raggedright\arraybackslash}p{0.32\textwidth}>{\raggedright\arraybackslash}X}",
        r"\caption{Coq/Rocq finite witness coverage map. The table is generated from \texttt{formal/coverage.json} and checked by \texttt{make verify}.}",
        r"\label{tab:coq-coverage-map}\\",
        r"\toprule",
        r"\TableHeaderRow Manuscript item & Coq/Rocq object & Scope \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"\TableHeaderRow Manuscript item & Coq/Rocq object & Scope \\",
        r"\midrule",
        r"\endhead",
        r"\midrule",
        r"\multicolumn{3}{r}{\footnotesize Continued on next page} \\",
        r"\endfoot",
        r"\bottomrule",
        r"\endlastfoot",
    ]
    for index, entry in enumerate(entries):
        if index % 2 == 1:
            lines.append(r"\rowcolor{tablerowbg}")
        lines.append(
            tex_escape(entry["paper_ref"])
            + " & "
            + tt(entry["coq_object"])
            + " & "
            + tex_escape(entry["scope"])
            + r" \\"
        )
    lines.extend(
        [
            r"\end{xltabular}",
            r"\endgroup",
            "",
        ]
    )
    return "\n".join(lines)


def validate(entries: list[dict[str, str]]) -> list[str]:
    tex = read(TEX_PATH)
    coq = read(COQ_PATH)
    labels = tex_labels(tex)
    theorem_labels = theorem_like_labels(tex)
    objects = coq_objects(coq)
    errors: list[str] = []

    ids = [entry["id"] for entry in entries]
    paper_labels = [entry["paper_label"] for entry in entries]
    coq_names = [entry["coq_object"] for entry in entries]

    for field, values in (("id", ids), ("paper_label", paper_labels), ("coq_object", coq_names)):
        duplicates = {value for value in values if values.count(value) > 1}
        for duplicate in sorted(duplicates):
            errors.append(f"duplicate {field}: {duplicate}")

    for entry in entries:
        if entry["kind"] != "finite_witness":
            errors.append(f"coverage entry has unsupported kind: {entry['id']}")
        if entry["status"] != "mechanized":
            errors.append(f"coverage entry is not mechanized: {entry['id']}")
        if entry["paper_label"] not in labels:
            errors.append(f"paper label not found: {entry['paper_label']}")
        if entry["coq_object"] not in objects:
            errors.append(f"Coq object not found: {entry['coq_object']}")

    covered_theorems = {entry["paper_label"] for entry in entries}
    for label in sorted(theorem_labels - covered_theorems):
        errors.append(f"theorem/proposition/lemma missing coverage entry: {label}")

    og3_objects = {name for name in objects if name.startswith("og3_")}
    covered_objects = set(coq_names)
    for name in sorted(og3_objects - covered_objects):
        errors.append(f"og3 Coq object missing coverage entry: {name}")

    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="write generated LaTeX table")
    parser.add_argument("--check", action="store_true", help="fail if generated table is stale")
    args = parser.parse_args()

    entries = load_manifest()
    errors = validate(entries)
    if errors:
        for error in errors:
            print(f"coverage error: {error}", file=sys.stderr)
        return 1

    generated = generate_table(entries)
    if args.write:
        TABLE_PATH.parent.mkdir(parents=True, exist_ok=True)
        TABLE_PATH.write_text(generated, encoding="utf-8")
        return 0

    if args.check:
        if not TABLE_PATH.exists():
            print(f"coverage error: generated table missing: {TABLE_PATH}", file=sys.stderr)
            return 1
        current = read(TABLE_PATH)
        if current != generated:
            print("coverage error: generated table is stale; run make formal-sync", file=sys.stderr)
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
